---
configs:
  - app_name: "some_app"
    log_path: "/var/log/some_app"
    cron_expression: "0 4 * * *"
    run_agent_name:
      - "dev"
    action:
      strategy: truncate
      from: top
      by: megabytes
      size: 2048
      days_old: 2

agents:
  - name: dev
    hostname: localhost
    port: 2000
    secret: b9d36fa4b6cd3d8a2f5527c792143bfc

server:
  host: "127.0.0.1"
  port: 7423
  type: tcp
