---
configs:
  ##?? TRUNCATE
  - app_name: "truncate_app"
    log_files_regexp: "/var/log/truncate_app"
    cron_expression: "30 10 * * *"
    run_agent_name:
      - "local"
    action:
      strategy: truncate
      from: top
      by: megabytes
      size: 2048

  ##?? ROTATE WITHOUT COMPRESS
  - app_name: "rotate_app_no_compress"
    log_files_regexp: "/var/log/rotate_app_no_compress"
    cron_expression: "30 11 * * *"
    run_agent_name:
      - "local"
      - "dev"
    action:
      strategy: rotate
      by: days
      size: 3
      delete_older_than_days: 7
      compress: false

  ##?? ROTATE WITH COMPRESS
  - app_name: "rotate_app_compress"
    log_files_regexp: "/var/log/rotate_app_compress"
    cron_expression: "25 10 * * *"
    run_agent_name:
      - "local"
      - "dev"
    action:
      strategy: rotate
      by: megabytes
      size: 4096
      delete_older_than_days: 7
      compress: true
      compression_type: gzip
      compression_level: 5

  ##?? ROTATE NO DELETE
  - app_name: "rotate_app_compress"
    log_files_regexp: "/var/log/rotate_app_compress"
    cron_expression: "0 11 * * *"
    run_agent_name:
      - "local"
      - "dev"
    action:
      strategy: rotate
      by: megabytes
      size: 4096
      compress: true
      compression_type: gzip
      compression_level: 7

  ##?? DELETE
  - app_name: "delete_app"
    log_files_regexp: "/var/log/delete_app"
    cron_expression: "25 10 * * *"
    run_agent_name:
      - "local"
      - "dev"
    action:
      strategy: delete
      delete_older_than_days: 3

agents:
  - name: dev
    hostname: localhost
    port: 2000
    secret: b9d36fa4b6cd3d8a2f5527c792143bfc

server:
  host: "127.0.0.1"
  port: 7423
  type: tcp
  time_zone: Asia/Nicosia
