---
configs:
  ##?? REAL PARTG
  - app_name: "truncate_app"
    logs_dir: "/var/log/cups"
    log_files_regexp: "access_log.*"
    cron_expression: "11 18 * * *"
    run_agent_names:
      - "local"
      - "dev"
    action:
      strategy: truncate
      from: top
      if:
        condition: days
        operator: ">"
        operand: 3

  ##?? TRUNCATE
  - app_name: "truncate_app"
    logs_dir: "/var/log/truncate_app"
    log_files_regexp: ".*"
    cron_expression: "35 17 * * *"
    run_agent_names:
      - "local"
    action:
      strategy: truncate
      from: top
      if:
        condition: size
        operator: ">"
        operand: 2048

  ##?? ROTATE WITHOUT COMPRESS
  - app_name: "rotate_app_no_compress"
    logs_dir: "/var/log/rotate_app_no_compress"
    log_files_regexp: ".*"
    cron_expression: "30 11 * * *"
    run_agent_names:
      - "local"
      - "dev"
    action:
      strategy: rotate
      if:
        condition: days
        operator: ">"
        operand: 3
      delete_archives_older_than_days: 7
      compress: false

  ##?? ROTATE WITH COMPRESS
  - app_name: "rotate_app_compress"
    logs_dir: "/var/log/rotate_app_compress"
    log_files_regexp: ".*"
    cron_expression: "25 10 * * *"
    run_agent_names:
      - "local"
      - "dev"
    action:
      strategy: rotate
      if:
        condition: size
        operator: ">"
        operand: 4096
      delete_archives_older_than_days: 7
      compress: true
      ##?? gzip
      compression_type: gzip
      ##?? Between 4-9
      compression_level: 5

  ##?? ROTATE NO DELETE
  - app_name: "rotate_app_compress"
    logs_dir: "/var/log/rotate_app_compress"
    log_files_regexp: ".*"
    cron_expression: "0 11 * * *"
    run_agent_names:
      - "local"
      - "dev"
    action:
      strategy: rotate
      if:
        condition: size
        operator: ">"
        operand: 4096
      compress: true
      compression_type: gzip
      compression_level: 7

  ##?? DELETE
  - app_name: "delete_app"
    logs_dir: "/var/log/delete_app"
    log_files_regexp: ".*"
    cron_expression: "25 10 * * *"
    run_agent_names:
      - "local"
      - "dev"
    action:
      strategy: delete
      if:
        ##?? days - size (size in mb)
        condition: days
        operator: ">"
        operand: 3

agents:
  - name: dev
    hostname: "127.0.0.1"
    port: 7424
    secret: b9d36fa4b6cd3d8a2f5527c792143bfc

server:
  host: "127.0.0.1"
  port: 7423
  type: tcp
  time_zone: Asia/Nicosia
