---
configs:
  ##?? ROTATE
  - app_name: "rotate_app"
    logs_dir: "/var/log/nginx"
    log_files_regexp: "access.log"
    cron_expression: "27 13 * * *"
    run_agent_names:
      - "dev"
    action:
      strategy: rotate
      if:
        condition: days
        operator: ">"
        operand: 3
      compress: true
      ##?? gzip
      compression_type: gzip
      ##?? Between 4-9
      compression_level: 5

  ##?? DELETE
  - app_name: "delete_app"
    logs_dir: "/var/log/php"
    log_files_regexp: 'laravel\.log\..*'
    cron_expression: "43 12 * * *"
    run_agent_names:
      - "dev"
    action:
      strategy: delete
      if:
        ##?? days - size (size in mb)
        condition: days
        operator: ">"
        operand: 3

  - app_name: "delete_app"
    logs_dir: "/var/log/postgres"
    log_files_regexp: 'postgresql-\w+\.log'
    cron_expression: "43 12 * * *"
    run_agent_names:
      - "dev"
    action:
      strategy: delete
      if:
        ##?? days - size (size in mb)
        condition: days
        operator: ">"
        operand: 3

agents:
  - name: dev
    hostname: "127.0.0.1"
    port: 7424
    secret: b9d36fa4b6cd3d8a2f5527c792143bfc

server:
  host: "127.0.0.1"
  port: 7423
  type: tcp
