FROM alpine

RUN apk add --no-cache bash coreutils libfaketime

COPY ./create-logs.sh /usr/local/bin
COPY ./live-logging.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/*.sh

RUN create-logs.sh

ENTRYPOINT ["/bin/bash"]
CMD ["live-logging.sh"]
