name: Unit & Coverage Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Unit-Testing:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zig 14
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - name: Zig build
        run: zig build

      - name: Build test binary
        run: zig build test-bin

      - name: Unit test
        run: zig build test

      - name: Run kcov coverage test
        uses: sudo-bot/action-kcov@latest
        with:
          cli-args: "--clean --exclude-region=//test-no-cover-start://test-no-cover-end --include-path=src/ zig-out/bin/unit_tests"
